# Generated by Django 5.0 on 2023-12-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('bajada', models.CharField(max_length=30)),
                ('fecha', models.CharField(max_length=30)),
                ('cuerpo', models.CharField(max_length=3000)),
            ],
        ),
    ]
