# Generated by Django 5.0 on 2024-03-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_publicaciones_imagen_alter_publicaciones_bajada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaciones',
            name='fecha',
            field=models.DateField(help_text='Por favor, ingrese la fecha en el formato DD/MM/YYYY.', max_length=30),
        ),
    ]
