# Generated by Django 5.0 on 2024-03-07 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_autor_publicaciones_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaciones',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
