# Generated by Django 5.0 on 2024-03-07 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_remove_publicaciones_autor_delete_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='autor',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
